# Introduction to Data Science 2022

# Week 1

## Exercise 1 | Matrix warm-up
<span style="background-color: #ccfff2"> *Note: You can find tutorials for NumPy and Pandas under 'Useful tutorials' in Moodle.*</span>

One of the most useful properties of any scientific programming language (Python with NumPy, R, Julia, etc) is that they allow us to work with matrices efficiently. Let's learn more about these features!

### 1.1 Basics

1. Let's start by creating two arrays <span style="background-color: #ccfff2"> A</span> and <span style="background-color: #ccfff2"> B</span> which each have the integers <span style="background-color: #ccfff2"> 0, 1, 2, ..., 1e7-1</span>. Use the normal arrays or lists of the programming language you are using, e.g. *list* or *[ ]* or *numpy.array()* in Python.

In [ ]:
import numpy as np

#create array with elements in the range from 0 to 1e7 - 1 (integers)
A = np.arange(int(1e7))
B = np.arange(int(1e7))

print('A = ', A)

: 

2. Create a function that uses a <span style="background-color: #ccfff2"> for loop</span> or equivalent to return a new array <span style="background-color: #ccfff2"> C</span>, which contains the <span style="background-color: #ccfff2"> element-wise sum of *A* and *B*</span>.

In [ ]:
def add_with_for(A,B):
    C = np.zeros(len(A)) # initialize new array
    
    for i in range(len(A)):
        C[i] = A[i] + B[i] # element-wise sum
    return C

print('C = ', add_with_for(A, B))

3. Next, let's use NumPy (or equivalent) to do the same. To try it out, add arrays A and B together using a library function, e.g. NumPy. Don't use loops, instead, find out how to add the two arrays directly. What do you notice in comparison to the previous function?

In [ ]:
C = np.add(A,B)
print('C = ', C) # Wow! So much faster!

### 1.2 Array manipulation

<span style="background-color: #ccfff2"> *Note: for the following exercises, only use NumPy or equivalent functions. Don't use any loops.* </span>
1. Create the following array:

*[hint: <span style="background-color: #ccfff2"> np.reshape</span>]*

In [4]:
# array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
#        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
#        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
#        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
#        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
#        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
#        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
#        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
#        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
#        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
arr1 = np.arange(100) #Set elements in the range from 0 to 99

arr1 = arr1.reshape((10,10)) #Reshape the array to have dimensions (10,10)

print('arr = ')
print(arr1)

2. Create the following array:

In [6]:
# array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

In [ ]:
arr2 = np.array([0.,1.])

arr2 = np.tile(arr2, 50) #repeat pattern 50 times

arr2 = arr2.reshape((10,10)) #reshape to desired dimensions (10,10)

print('arr = ')
print(arr2)

3. Create the following array (D):

In [8]:
# array([[0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

In [ ]:
D = np.ones((10,10)) # Create a (10,10) array consisting only of ones

np.fill_diagonal(D, 0) # Switch all the elements of the diagonal to zero

print('D = ')
print(D)

4. Create the following array (E):

In [10]:
# array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [0., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
E = np.rot90(D)

print('E = ')
print(E)

5. Call the last two matrices <span style="background-color: #ccfff2">D</span> and <span style="background-color: #ccfff2">E</span>, respectively. Show that the determinant of their product (matrix multiplication) is the same as the product of their determinants. That is calculate both <span style="background-color: #ccfff2">det(DE)</span> and <span style="background-color: #ccfff2">det(D) * det(E)</span>, and show that they are the same. Is it a coincidence? (I think not)

In [ ]:
D_det = np.linalg.det(D) # determinant of D

E_det = np.linalg.det(E) # determinant of E

print(D_det * E_det)

prod = np.dot(D, E) #product matrix

prod_det = np.linalg.det(prod) #determinant of product matrix

print(prod_det)

### 1.3 Slicing

Array slicing is a powerful way to extract data from an array. Let's practice array slicing with the following exercises!

1. Load the [California housing dataset](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_california_housing.html). The data should be a matrix of shape <span style="background-color: #ccfff2">(20640, 8)</span>, that is 20640 rows and 8 columns. Use the <span style="background-color: #ccfff2">.shape</span> attribute of NumPy arrays to verify this. Here's a [description of the fields](https://scikit-learn.org/stable/datasets/real_world.html#california-housing-dataset).

In [ ]:
from sklearn.datasets import fetch_california_housing

cali = fetch_california_housing()

print(cali.data.shape) # print dataset shape
print(cali['DESCR']) # print dataset description

2. Select rows where the average number of bedrooms <span style="background-color: #ccfff2">(AveBedrms)</span> is higher than 2. The first few row indices should be <span style="background-color: #ccfff2">710,  1023,  1024, ...</span> (zero-indexed). Count these houses - how many rows are selected? *[hint: <span style="background-color: #ccfff2">np.where</span>]*

In [ ]:
# Find row indices where average number of bedrooms > 2
houses = np.where(cali.data[:, 3] > 2)

houses_count = houses[0].shape[0] # Count rows

print('Houses with more bedrooms (row indices) = ', houses)
print('Number of houses (rows) with more bedrooms = ', houses_count)

3. Select the rows where the median house age (i.e. median in each block group) <span style="background-color: #ccfff2">(HouseAge)</span> is between 1 and 3 years (inclusive). There should be **124** of these.

In [ ]:
house_age = np.where((cali.data[:, 1] >= 1)&(cali.data[:, 1] <= 3))

print('Houses selected within HouseAge interval (row indices) = ', house_age)
print('Number of houses (rows) within HouseAge interval = ', house_age[0].shape[0])

4. Find the mean of the block group population <span style="background-color: #ccfff2">(Population)</span> for homes whose median value is more than 25000 USD (the target variable). It should be around **1425.68**.

In [ ]:
homes = np.where(cali.target > 0.25) # Houses with median value over $25,000

pop = cali.data[homes, 4] # From the selected rows, get the population column

mean_pop = np.mean(pop) # calculate mean of population

print("Mean block group population = ", mean_pop)

**Remember to submit your code on Moodle. You can return this Jupyter notebook (.ipynb) or .py, .R, etc depending on your programming preferences.**

## Exercise 2 | Working with text data

Next, let's look into some text data. We will be looking into Amazon reviews, and the steps needed to transform a raw dataset into a format more suitable for prediction tasks.

1. Download the automotive 5-core dataset from [here](https://jmcauley.ucsd.edu/data/amazon_v2/categoryFilesSmall/Automotive_5.json.gz). Next, you can extract the data in <span style="background-color: #ccfff2">JSON</span> format. You can also download one of the bigger ones, if you are feeling ambitious. Open the JSON file. Access the <span style="background-color: #ccfff2">reviewText</span> field, which contains the unstructured review text written by the user.

In [ ]:
import pandas as pd
import string

data = pd.read_json("Automotive_5.json", lines=True)

print('A review example: ', data.iloc[1]['reviewText'])

2. Next, let's follow some steps to normalize the text data.

When dealing with natural language, it is important to notice that while, for example, the words "Copper" and "copper" are represented by two different strings, they have the same meaning. When applying statistical methods on this data, it is useful to ensure that words with the same meaning are represented by the same string.

* <span style="background-color: #ccfff2">Downcasing</span>: Let's first downcase the contents of the <span style="background-color: #ccfff2">reviewText</span> field.

In [ ]:
data['reviewText'] = data['reviewText'].str.lower()

print('Downcasing example: ', data.iloc[1]['reviewText'])

3. Let's continue with punctuation and stop word removal. Stop words are words like "and", "the", etc. They are usually very common words that have little to do with the actual content matter. There's plenty openly available lists of stop words for almost any (natural) language.

* <span style="background-color: #ccfff2">Punctuation and stop-word removal</span>: Let's now remove all punctuation, as well as the stop words. You can find a stop word list for English, e.g. [here](https://gist.github.com/xldrkp/4a3b1a33f10d37bedbe0068f2b4482e8#file-stopwords-en-txt). Save the stopwords in the file as "stopwords-en.txt".

In [ ]:
data['reviewText'] = data['reviewText'].str.replace(r'[^\w\s]+', '', regex=True)

print('Example after removing punctuation: ', data.iloc[1]['reviewText'])

In [ ]:
#remove stop words
with open("stopwords-en.txt") as f:
    stopwords = set(f.read().split("\n"))
    
data["reviewText"] = data['reviewText'].apply(lambda x: ' '.join([word for word in str(x).split() if word not in (stopwords)]))
print('Example after removing stopwords: ', data.iloc[1]['reviewText'])

4. Let's continue with stemming. For example, while the words "swims" and "swim" are different strings, they both refer to swimming. [Stemming](https://en.wikipedia.org/wiki/Stemming) refers to the process of mapping words in inflected form to their base form, for instance: swims -> swim.

* <span style="background-color: #ccfff2">Stemming</span>: Apply a stemmer on the paragraphs, so that inflected forms are mapped to the base form. For example, for Python the popular natural language toolkit [nltk](http://www.nltk.org/howto/stem.html) has an easy to use stemmer. In case you are using R, you can try the [Snowball stemmer](https://www.rdocumentation.org/packages/corpus/versions/0.10.2/topics/stem_snowball). You can find out how to install nltk from [here](https://www.nltk.org/install.html). It will take a while to run! So, grab a coffee and wait :D

In [ ]:
from nltk.stem.porter import *

ps = PorterStemmer() # Takes a while
data["reviewText"] = data["reviewText"].apply(lambda x: ' '.join([ps.stem(word) for word in str(x).split()]))

print('Review example after stemming: ', data.iloc[1]['reviewText'])

5. Finally, filter the data by selecting reviews where the field <span style="background-color: #ccfff2">overall</span> is 4 or 5, and store the review texts in file <span style="background-color: #ccfff2">pos.txt</span>. Similarly, select reviews with rating 1 or 2 and store the reviews in file <span style="background-color: #ccfff2">neg.txt</span>. Ignore the reviews with overall rating 3. Each line in the two files should contain exactly one preprocessed review text without the rating.

In [ ]:
pos = []
neg = []

for row in range(len(data)):
    if data.iloc[row]["overall"] > 3:
        pos.append(data.iloc[row]["reviewText"])
    elif data.iloc[row]["overall"] < 3:
        neg.append(data.iloc[row]["reviewText"])

with open("pos.txt", 'w') as f:
    f.write("\n".join(pos))

with open("neg.txt", 'w') as f:
    f.write("\n".join(neg))
    
# Check the generated files!

Having created two collections of positive and negative reviews respectively, you may wish to take a quick look to see how the review texts differ between them (positive vs negative). Keep these files, as we will be using this data later to experiment with machine learning methods.

**Remember to submit your code on Moodle. You can return this Jupyter notebook (.ipynb) or .py, .R, etc depending on your programming preferences. No need to submit the text files.**